package com.eardefender.model.response;

import com.eardefender.model.SegmentPrediction;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.util.List;

@Schema(description = "Response model for prediction of a file")
@Builder
@Data
public class PredictionResultResponse {

    @Schema(description = "The URL link associated with the prediction result",
            example = "https://example.com/prediction")
    private String link;

    @Schema(description = "Timestamp of the prediction result in ISO 8601 format (YYYY-MM-DDThh:mm:ssTZD)",
            example = "2024-10-10T14:30:00Z")
    private String timestamp;

    @Schema(description = "The name of the model used for predictions",
            example = "example-model")
    private String model;

    @Schema(description = "List of predictions generated by the model")
    private List<SegmentPrediction> modelPredictions;
}
